-- 用户管理

CREATE TABLE `t_user` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `account` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '手机号（登录账号）',
  `email` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '邮箱（可选）',
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '密码哈希',
  `first_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '名',
  `last_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '姓',
  `avatar` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '头像',
  `id_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'id_card' COMMENT '证件类型 id_card身份证 passport护照',
  `id_number` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '证件号码',
  `id_valid_until` date DEFAULT NULL COMMENT '证件有效期(仅身份证)',
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '当前住址',
  `invitation_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '邀请码',
  `pid` int unsigned NOT NULL DEFAULT '0' COMMENT '上级用户ID',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态 0停用 1启用',
  `tent_score` int NOT NULL DEFAULT '500' COMMENT 'Tent Score信用分',
  `balance` decimal(12, 2) NOT NULL DEFAULT '0.00' COMMENT '钱包余额',
  `last_active_at` datetime DEFAULT NULL COMMENT '最后活跃时间',
  `last_latitude` decimal(10, 7) DEFAULT NULL COMMENT '最后上报纬度',
  `last_longitude` decimal(10, 7) DEFAULT NULL COMMENT '最后上报经度',
  `last_location_at` datetime DEFAULT NULL COMMENT '最后位置上报时间',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account` (`account`),
  UNIQUE KEY `uk_invitation_code` (`invitation_code`),
  KEY `idx_status` (`status`),
  KEY `idx_id_number` (`id_number`),
  KEY `idx_pid` (`pid`),
  KEY `idx_last_location_at` (`last_location_at`),
  KEY `idx_last_lat_lng` (`last_latitude`, `last_longitude`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';
